### ISSUE TITLE
Fabric and Quilt are not running

### ISSUE THREAD

**Issue by powerbute** [Natoune/open_launcher_rs#1]
Vanilla starts normally, but an error is returned when trying to run Fabric or Quilt

```
Progress: downloading_libraries 72/72 (100%)
thread 'main' panicked at C:\Users\Powerbute\.cargo\registry\src\index.crates.io-6f17d22bba15001f\open_launcher-1.5.4\src\libraries.rs:175:34:
IndexMap: key not found
Progress channel closed
```

**Comment by Natoune** [comment]
Fixed for [v1.5.5](https://crates.io/crates/open_launcher/1.5.5) (commit: dd3ed50256da663e09ec9df2fc59db8b8c4f4d22).
I'm really sorry for the 2 months of waiting 😅...
